### ISSUE TITLE
TypeScript type declaration file

### ISSUE THREAD

**Issue by geopic** [acuminous/zUnit#1]
If you want I can write a TypeScript type declaration file for this package so that TS developers can utilise the type-checking feature of the language as they use this package. Let me know if you are interested.

**Comment by cressie176** [comment]
Hi @geopic,
Sorry for not responding earlier - I missed the notification. Thanks for the offer, zUnit's a little volatile still, so now probably isn't the best time for type definitions. I might  take you up on this in the near future if that's OK?

**Comment by cressie176** [comment]
Hi @geopic,
I've made the changes I wanted and started using zUnit in anger on my other open source projects, so it should be fairly stable now. I'd be delighted to receive a PR with TypeScript type declarations if you still have the  time.
Best,
Steve

**Comment by geopic** [comment]
Sounds good @cressie176, I'll get down to it now. :smiley: Cheers mate

**Comment by cressie176** [comment]
Hi @geopic,

Thanks again for contributing the type definitions. I've merged and validated them using a simple test script. I noticed a couple of issues, which I've tried to fix [here](https://github.com/acuminous/zUnit/commit/f8eb38ab063ffa91c49035b291daef68e8ff3cf9)

I'm new to typescript so quite possible I've misunderstood something. If you have time are you able to double check?

If everything's OK I'll go ahead and publish a new release to npm.

Thanks.

**Comment by geopic** [comment]
Those changes are fine @cressie176, looks like I made a few errors and oversights, particularly on lines 56 and 74 with `'string'` :man_facepalming: Thanks for getting back to me anyway and for including it in the new release.

**Comment by cressie176** [comment]
Thanks @geopic, I really appreciate that you took the time to contribute the definitions, and again took time to review. Publishing now.

**Comment by cressie176** [comment]
Published as 3.0.4. Thanks again.
